### ISSUE TITLE
advice

### ISSUE THREAD

**Issue by ntgeralt** [maomiui/googlevoice#1]
分享两点建议：
1.我用PC客户端Netch+v2ray节点成功注册了。路由器开不开翻墙都没事。netch接管整个电脑链路。
netch选择4 绕过lan和China，测试评测70%+

2.您说的“打开 https://ipdata.co/，看到显示 isp 表示家庭用户，如是代理托管建议更换路线。”
显示ISP表示家庭用户代表不推荐，应该换线路吗？

**Comment by ssnhd** [comment]
* 显示 `isp` 是最佳的意思；
* 如果显示 `type: "hosting"`，建议更换路线。

**Comment by ntgeralt** [comment]
嗯。我看只写isp，没看解释是好是坏

**Comment by ntgeralt** [comment]
分享个实例：
GCP开一台美国，跑v2ray，配合netch上gv，直接选号。
谷歌下短信接收平台，收条短信，搞定
