### ISSUE TITLE
2.35$只能使用一次吗？

### ISSUE THREAD

**Issue by scramjetFoam** [maomiui/googlevoice#12]
您好，我想问下2.35$只能接一次码，注册一个gv号吗？

**Comment by ssnhd** [comment]
是的，使用一次，如果你的节点非原生导致注册失败没有下号，钱等于浪费。

文中提供的接码平台仅供参考，你也可以选择其他更优质平台。

**Comment by scramjetFoam** [comment]
> 是的，使用一次，如果你的节点非原生导致注册失败没有下号，钱等于浪费。
> 
> 文中提供的接码平台仅供参考，你也可以选择其他更优质平台。

好的，谢谢
