### ISSUE TITLE
其实不如直接买一个转移到自己账户上

### ISSUE THREAD

**Issue by WayneCommand** [maomiui/googlevoice#13]
我是冲了5刀 接了两次码，都没有下号。

然后无聊在某宝搜到了，7块钱搞定 还是自动发货的。

虽然号不能自己选就是了，至少转移到自己的Google账户上是没什么问题的。

**如果你看到了这个，可以试试，少走些弯路。**

**Comment by Zenas1023** [comment]
感谢😃还是某宝好用
