### ISSUE TITLE
GV无法拨出电话

### ISSUE THREAD

**Issue by Liujun3712** [maomiui/googlevoice#14]
可以正常收短信、接收电话，但是无法拨出，请问有人知道怎么解决吗？

**Comment by ssnhd** [comment]
参考文内 客户端

**Comment by Liujun3712** [comment]
> 参考文内 客户端

已经设置了，但是gv之间互相呼叫无法接通。以前拨打过的万豪美国的号码可以接通。拨打国内的手机号码也不行。

**Comment by lhqx** [comment]
除了客户端设置，剩下的就是网络，使用其他设备重新安装实测无法复现。

**Comment by ssnhd** [comment]
> > 参考文内 客户端
> 
> 已经设置了，但是gv之间互相呼叫无法接通。以前拨打过的万豪美国的号码可以接通。拨打国内的手机号码也不行。

除了客户端设置，剩下的就是网络，使用其他设备重新安装实测无法复现。
