### ISSUE TITLE
FAILED_PRECONDITION

### ISSUE THREAD

**Issue by xiaobinqt** [maomiui/googlevoice#15]
请教在转号时一直出现 

***由于某些原因，无法完成号码转移**

![image](https://user-images.githubusercontent.com/23259661/169436344-91262b0c-f3dd-4605-9a59-3aba1d6baf5b.png)

是什么原因 ?

**Comment by httpsColon** [comment]
风控了呗

**Comment by ssnhd** [comment]
转移号码建议一周后操作，其次需要美国原生IP，切勿频繁操作容易被谷歌封号。
在 2022年5月20日 +0800 AM10:26，萧十一郎 ***@***.***>，写道：
