### ISSUE TITLE
verifywithsms 充值成功了， 金额不显示

### ISSUE THREAD

**Issue by yimao009** [maomiui/googlevoice#2]
您好，有俩个问题
第一是我 verifywithsms 这上边充值2.1 余额还是0 难道我姿势不对吗

第二是我验证了，选的gv号码， gv页面显示没有我选的号码，还提示让我选号码

疯了。。。

**Comment by ssnhd** [comment]
第一点不清楚，也没遇到过。
第二点说明你注册未成功，和你的美国路线 IP 有关，建议更换路线。
在 2020年5月11日 +0800 PM4:43，ChineseDragon <notifications@github.com>，写道：

**Comment by yoloon** [comment]
大佬求救，我现在也是遇到第一步了，充值成功不显示余额，已经三天了。你这边最后解决了吗？谢谢！

**Comment by ssnhd** [comment]
该网站下方有Telegram，你可以联系他们，也可以在PayPal里申请退款处理。
在 2020年6月15日 +0800 PM11:01，yoloon <notifications@github.com>，写道：
