### ISSUE TITLE
 sms-activate接码可用（但是是恢复号码）

### ISSUE THREAD

**Issue by latinisation** [maomiui/googlevoice#20]
新注册不知能否可以，但是收回号码再申请拿回是可用的。付费接码，我选择美国（物理)号码接码成功收到验证码短信。[网址](https://sms-activate.io/)

**Comment by Rain021300** [comment]
> 新注册不知能否可以，但是收回号码再申请拿回是可用的。付费接码，我选择美国（物理)号码接码成功收到验证码短信。[网址](https://sms-activate.io/)

今天获取的都是虚拟号，200+卢布的也是虚拟号，你获取的是物理号码？

**Comment by latinisation** [comment]
> > 新注册不知能否，但是可以收回号码再申请回执。付费接听，我选择美国（物理）号码接听成功后会收到验证短信[。](https://sms-activate.io/)
> 
> 今天获得的都是虚拟号，200+卢布的也是虚拟号，你获得的是物理号码吗？

我用的是这个
![屏幕截图 2024-06-30 195904](https://github.com/ssnhd/googlevoice/assets/26472091/57a77ddd-3651-4d41-b822-a1c24f9ec659)
