### ISSUE TITLE
短信平台无法充值

### ISSUE THREAD

**Issue by ipdor** [maomiui/googlevoice#3]
在接收短信的网站上当充值时点击paypal会弹出一个小框，但是每次都秒消失，换过很多浏览器、设备都是这样，无法充值

**Comment by ly2gz** [comment]
我现在也是，请问解决了么

**Comment by ipdor** [comment]
后来我看了youtube上一个视频，博主试了这种方法也失败了，所以后面我没有尝试过。鉴于申请太麻烦，我从淘宝上10块钱买了个账号，没再试了




------------------ 原始邮件 ------------------
发件人: ly2gz <notifications@github.com&gt;
发送时间: 2020年8月27日 15:59
收件人: masonme/GoogleVoice <GoogleVoice@noreply.github.com&gt;
抄送: Nate <ylvan@foxmail.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[masonme/GoogleVoice] 短信平台无法充值 (#3)





 
我现在也是，请问解决了么
