### ISSUE TITLE
不成啊

### ISSUE THREAD

**Issue by clubfocus** [maomiui/googlevoice#8]
按照教程仔细操作，甚至为了ip更安全改了操作系统的时间和浏览器语言保持IP一致，还是没成功啊啊啊啊啊，试了两次，4.7刀，午饭不吃了

**Comment by ssnhd** [comment]
文内提到检测接码号码是否支持方法，如果支持，即IP问题。

**Comment by clubfocus** [comment]
> 文内提到检测接码号码是否支持方法，如果支持，即IP问题。

我也想是IP问题，可惜找不到原生美国IP的vpn，大佬有没有推荐。。PS.p卡里只剩3刀了
